version: 2.1
jobs:
  test:
     docker:
        - image: cimg/openjdk:19.0.2
        - image: cimg/maven:3.8.7
      steps:
        - checkout
        - run: java --version
        - run: mvn clean install

# Invoke jobs via workflows
#https://circleci.com/developer/images
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  spark-test-workflow:
    jobs:
      - test
