version: 2.1

# Invoke jobs via workflows
#https://circleci.com/developer/images
#
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
#
jobs:
  test:
    docker:
      - image: cimg/openjdk:19.0.2
    steps:
      - checkout
      - run: java --version
      - run: mvn clean
        
workflows:
  spark-test-workflow:
    jobs:
      - test
      
